<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="FluentMigrator" />
    <PackageReference Include="FluentMigrator.Runner" />
    <PackageReference Include="FluentMigrator.Runner.SQLite" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Darhous.Archive.Core\Darhous.Archive.Core.csproj" />
    <ProjectReference Include="..\Darhous.Archive.Contracts\Darhous.Archive.Contracts.csproj" />
    <ProjectReference Include="..\Darhous.Archive.Application\Darhous.Archive.Application.csproj" />
    <ProjectReference Include="..\Darhous.Archive.Configuration\Darhous.Archive.Configuration.csproj" />
  </ItemGroup>

</Project>
