<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Darhous.Archive.Modules.Ai\Darhous.Archive.Modules.Ai.csproj" />
    <ProjectReference Include="..\..\src\Darhous.Archive.Configuration\Darhous.Archive.Configuration.csproj" />
    <ProjectReference Include="..\..\src\Darhous.Archive.Security\Darhous.Archive.Security.csproj" />
  </ItemGroup>

</Project>
