<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="PdfPig" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="MimeKit" />
    <PackageReference Include="MsgReader" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Darhous.Archive.Core\Darhous.Archive.Core.csproj" />
    <ProjectReference Include="..\..\Darhous.Archive.Contracts\Darhous.Archive.Contracts.csproj" />
    <ProjectReference Include="..\..\Darhous.Archive.Application\Darhous.Archive.Application.csproj" />
  </ItemGroup>

</Project>
