<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <Using Include="Xunit" />
    <ProjectReference Include="../../src/Modules/Darhous.Archive.Modules.Ocr/Darhous.Archive.Modules.Ocr.csproj" />
    <ProjectReference Include="../../src/Darhous.Archive.Ocr.Worker/Darhous.Archive.Ocr.Worker.csproj" />
    <ProjectReference Include="../../src/Darhous.Archive.Persistence/Darhous.Archive.Persistence.csproj" />
    <ProjectReference Include="../../src/Modules/Darhous.Archive.Modules.Documents/Darhous.Archive.Modules.Documents.csproj" />
    <ProjectReference Include="../../src/Darhous.Archive.Audit/Darhous.Archive.Audit.csproj" />
  </ItemGroup>
</Project>
