<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon></ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Darhous.Archive.Core\Darhous.Archive.Core.csproj" />
    <ProjectReference Include="..\Darhous.Archive.Application\Darhous.Archive.Application.csproj" />
    <ProjectReference Include="..\Darhous.Archive.Configuration\Darhous.Archive.Configuration.csproj" />
    <ProjectReference Include="..\Darhous.Archive.Security\Darhous.Archive.Security.csproj" />
    <ProjectReference Include="..\Darhous.Archive.Persistence\Darhous.Archive.Persistence.csproj" />
    <ProjectReference Include="..\Darhous.Archive.Audit\Darhous.Archive.Audit.csproj" />
    <ProjectReference Include="..\Modules\Darhous.Archive.Modules.Documents\Darhous.Archive.Modules.Documents.csproj" />
    <ProjectReference Include="..\Modules\Darhous.Archive.Modules.Folders\Darhous.Archive.Modules.Folders.csproj" />
    <ProjectReference Include="..\OfficialPlugins\Darhous.Search.SqliteFts\Darhous.Search.SqliteFts.csproj" />
  </ItemGroup>

</Project>
